// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/expense_service.proto

package expense

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message representing a single Expense entity
type ExpenseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Date          int64                  `protobuf:"varint,5,opt,name=date,proto3" json:"date,omitempty"` // Unix timestamp in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpenseMessage) Reset() {
	*x = ExpenseMessage{}
	mi := &file_proto_expense_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpenseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseMessage) ProtoMessage() {}

func (x *ExpenseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseMessage.ProtoReflect.Descriptor instead.
func (*ExpenseMessage) Descriptor() ([]byte, []int) {
	return file_proto_expense_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExpenseMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExpenseMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExpenseMessage) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ExpenseMessage) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ExpenseMessage) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

// Request and Response for creating a new expense
type CreateExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Date          int64                  `protobuf:"varint,4,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpenseRequest) Reset() {
	*x = CreateExpenseRequest{}
	mi := &file_proto_expense_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseRequest) ProtoMessage() {}

func (x *CreateExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseRequest.ProtoReflect.Descriptor instead.
func (*CreateExpenseRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExpenseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateExpenseRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateExpenseRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateExpenseRequest) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

type CreateExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Supabase generated UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpenseResponse) Reset() {
	*x = CreateExpenseResponse{}
	mi := &file_proto_expense_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseResponse) ProtoMessage() {}

func (x *CreateExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseResponse.ProtoReflect.Descriptor instead.
func (*CreateExpenseResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateExpenseResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request and Response for fetching all expenses
type GetExpensesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpensesRequest) Reset() {
	*x = GetExpensesRequest{}
	mi := &file_proto_expense_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpensesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpensesRequest) ProtoMessage() {}

func (x *GetExpensesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpensesRequest.ProtoReflect.Descriptor instead.
func (*GetExpensesRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_service_proto_rawDescGZIP(), []int{3}
}

type GetExpensesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expenses      []*ExpenseMessage      `protobuf:"bytes,1,rep,name=expenses,proto3" json:"expenses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpensesResponse) Reset() {
	*x = GetExpensesResponse{}
	mi := &file_proto_expense_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpensesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpensesResponse) ProtoMessage() {}

func (x *GetExpensesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpensesResponse.ProtoReflect.Descriptor instead.
func (*GetExpensesResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetExpensesResponse) GetExpenses() []*ExpenseMessage {
	if x != nil {
		return x.Expenses
	}
	return nil
}

// Request and Response for deleting an expense
type DeleteExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpenseRequest) Reset() {
	*x = DeleteExpenseRequest{}
	mi := &file_proto_expense_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpenseRequest) ProtoMessage() {}

func (x *DeleteExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpenseRequest.ProtoReflect.Descriptor instead.
func (*DeleteExpenseRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteExpenseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpenseResponse) Reset() {
	*x = DeleteExpenseResponse{}
	mi := &file_proto_expense_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpenseResponse) ProtoMessage() {}

func (x *DeleteExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpenseResponse.ProtoReflect.Descriptor instead.
func (*DeleteExpenseResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteExpenseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request and Response for managing monthly budget
type GetBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"` // format YYYY-MM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetRequest) Reset() {
	*x = GetBudgetRequest{}
	mi := &file_proto_expense_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetRequest) ProtoMessage() {}

func (x *GetBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetRequest.ProtoReflect.Descriptor instead.
func (*GetBudgetRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetBudgetRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

type GetBudgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetResponse) Reset() {
	*x = GetBudgetResponse{}
	mi := &file_proto_expense_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetResponse) ProtoMessage() {}

func (x *GetBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetResponse.ProtoReflect.Descriptor instead.
func (*GetBudgetResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetBudgetResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SetBudgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"` // format YYYY-MM
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBudgetRequest) Reset() {
	*x = SetBudgetRequest{}
	mi := &file_proto_expense_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBudgetRequest) ProtoMessage() {}

func (x *SetBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBudgetRequest.ProtoReflect.Descriptor instead.
func (*SetBudgetRequest) Descriptor() ([]byte, []int) {
	return file_proto_expense_service_proto_rawDescGZIP(), []int{9}
}

func (x *SetBudgetRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *SetBudgetRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type SetBudgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBudgetResponse) Reset() {
	*x = SetBudgetResponse{}
	mi := &file_proto_expense_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBudgetResponse) ProtoMessage() {}

func (x *SetBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_expense_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBudgetResponse.ProtoReflect.Descriptor instead.
func (*SetBudgetResponse) Descriptor() ([]byte, []int) {
	return file_proto_expense_service_proto_rawDescGZIP(), []int{10}
}

func (x *SetBudgetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_expense_service_proto protoreflect.FileDescriptor

const file_proto_expense_service_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/expense_service.proto\x12\aexpense\"~\n" +
	"\x0eExpenseMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x12\n" +
	"\x04date\x18\x05 \x01(\x03R\x04date\"t\n" +
	"\x14CreateExpenseRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04date\x18\x04 \x01(\x03R\x04date\"'\n" +
	"\x15CreateExpenseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12GetExpensesRequest\"J\n" +
	"\x13GetExpensesResponse\x123\n" +
	"\bexpenses\x18\x01 \x03(\v2\x17.expense.ExpenseMessageR\bexpenses\"&\n" +
	"\x14DeleteExpenseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteExpenseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\x10GetBudgetRequest\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\"+\n" +
	"\x11GetBudgetResponse\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\"@\n" +
	"\x10SetBudgetRequest\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"-\n" +
	"\x11SetBudgetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x82\x03\n" +
	"\x0eExpenseService\x12N\n" +
	"\rCreateExpense\x12\x1d.expense.CreateExpenseRequest\x1a\x1e.expense.CreateExpenseResponse\x12H\n" +
	"\vGetExpenses\x12\x1b.expense.GetExpensesRequest\x1a\x1c.expense.GetExpensesResponse\x12N\n" +
	"\rDeleteExpense\x12\x1d.expense.DeleteExpenseRequest\x1a\x1e.expense.DeleteExpenseResponse\x12B\n" +
	"\tGetBudget\x12\x19.expense.GetBudgetRequest\x1a\x1a.expense.GetBudgetResponse\x12B\n" +
	"\tSetBudget\x12\x19.expense.SetBudgetRequest\x1a\x1a.expense.SetBudgetResponseB6Z4github.com/homebudget/backend/internal/proto/expenseb\x06proto3"

var (
	file_proto_expense_service_proto_rawDescOnce sync.Once
	file_proto_expense_service_proto_rawDescData []byte
)

func file_proto_expense_service_proto_rawDescGZIP() []byte {
	file_proto_expense_service_proto_rawDescOnce.Do(func() {
		file_proto_expense_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_expense_service_proto_rawDesc), len(file_proto_expense_service_proto_rawDesc)))
	})
	return file_proto_expense_service_proto_rawDescData
}

var file_proto_expense_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_expense_service_proto_goTypes = []any{
	(*ExpenseMessage)(nil),        // 0: expense.ExpenseMessage
	(*CreateExpenseRequest)(nil),  // 1: expense.CreateExpenseRequest
	(*CreateExpenseResponse)(nil), // 2: expense.CreateExpenseResponse
	(*GetExpensesRequest)(nil),    // 3: expense.GetExpensesRequest
	(*GetExpensesResponse)(nil),   // 4: expense.GetExpensesResponse
	(*DeleteExpenseRequest)(nil),  // 5: expense.DeleteExpenseRequest
	(*DeleteExpenseResponse)(nil), // 6: expense.DeleteExpenseResponse
	(*GetBudgetRequest)(nil),      // 7: expense.GetBudgetRequest
	(*GetBudgetResponse)(nil),     // 8: expense.GetBudgetResponse
	(*SetBudgetRequest)(nil),      // 9: expense.SetBudgetRequest
	(*SetBudgetResponse)(nil),     // 10: expense.SetBudgetResponse
}
var file_proto_expense_service_proto_depIdxs = []int32{
	0,  // 0: expense.GetExpensesResponse.expenses:type_name -> expense.ExpenseMessage
	1,  // 1: expense.ExpenseService.CreateExpense:input_type -> expense.CreateExpenseRequest
	3,  // 2: expense.ExpenseService.GetExpenses:input_type -> expense.GetExpensesRequest
	5,  // 3: expense.ExpenseService.DeleteExpense:input_type -> expense.DeleteExpenseRequest
	7,  // 4: expense.ExpenseService.GetBudget:input_type -> expense.GetBudgetRequest
	9,  // 5: expense.ExpenseService.SetBudget:input_type -> expense.SetBudgetRequest
	2,  // 6: expense.ExpenseService.CreateExpense:output_type -> expense.CreateExpenseResponse
	4,  // 7: expense.ExpenseService.GetExpenses:output_type -> expense.GetExpensesResponse
	6,  // 8: expense.ExpenseService.DeleteExpense:output_type -> expense.DeleteExpenseResponse
	8,  // 9: expense.ExpenseService.GetBudget:output_type -> expense.GetBudgetResponse
	10, // 10: expense.ExpenseService.SetBudget:output_type -> expense.SetBudgetResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_expense_service_proto_init() }
func file_proto_expense_service_proto_init() {
	if File_proto_expense_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_expense_service_proto_rawDesc), len(file_proto_expense_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_expense_service_proto_goTypes,
		DependencyIndexes: file_proto_expense_service_proto_depIdxs,
		MessageInfos:      file_proto_expense_service_proto_msgTypes,
	}.Build()
	File_proto_expense_service_proto = out.File
	file_proto_expense_service_proto_goTypes = nil
	file_proto_expense_service_proto_depIdxs = nil
}
